name: ci
on:
  push:
    branches:
      - master
      - main
      - "1.2"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mike
      - run: git config user.name ci-bot
      - run: git config user.email ci-bot@example.com
      - run: mike deploy 1.2 godot-3.4
