name: ci
on:
  push:
    branches:
      - master
      - main
      - "1.2"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mike
      - run: mike deploy 2.0.1 last godot-4.0
      - run: mike mike set-default last
